# These are supported funding model platforms
# Uncomment and add your links to enable the Sponsor button.

# github: [username]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# custom: ['https://example.com']